spring:
  application:
    name: ribbon-consumer
server:
  port: 9090
eureka:
  client:
     serviceUrl:
     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
